# Generated by Django 5.2.2 on 2025-06-06 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('products', models.ManyToManyField(related_name='products', to='products.product')),
            ],
        ),
    ]
