# Generated by Django 5.0.1 on 2025-06-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_product_rating_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
