# Generated by Django 5.0.1 on 2025-06-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(default='-', max_length=32, null=True),
        ),
    ]
