# Generated by Django 5.0.1 on 2025-06-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='generation',
            field=models.CharField(blank=True, default='-', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.CharField(blank=True, default='-', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, default='-', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='-', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='part_number',
            field=models.CharField(blank=True, default='-', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(blank=True, default='-', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(blank=True, default='Новое', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_m',
            field=models.CharField(blank=True, default='шт', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vincode',
            field=models.CharField(blank=True, default='-', max_length=32, null=True),
        ),
    ]
